#ifndef _CTRLIDS_H_
#define _CTRLIDS_H_

/*
** This file is auto-generated by the MX800 Form Manager tool.
** Do not modify the contents of this file by hand!
*/

/* Control IDs for Form WELCOME */
#define WELCOME_BTN_1                    1
#define WELCOME_LBL_1                    2

/* Control IDs for Form SWIPE */
#define SWIPE_LBL_1                      1
#define SWIPE_ANI_1                      2

#endif /* _CTRLIDS_H_ */
